export { default as Starter } from './assets/StarterandAlternater.jpg'
export { default as Airfilter } from './assets/airfilter.jpg'
export { default as Breakpadchange } from './assets/breakpadchange.jpg'
export { default as Breakpadchange1 } from './assets/breakpadchange1.jpg'
export { default as Bulbs } from './assets/bulbs.jpg'
export { default as Bulbs1 } from './assets/bulb1.jpg'
export { default as Bulbs2 } from './assets/bulb2.jpg'
export { default as Diagnostics } from './assets/diagnostics.jpg'
export { default as Engines } from './assets/engines.jpg'
export { default as Engines1 } from './assets/engines1.jpg'
export { default as Fuelpump } from './assets/fuelpump.jpg'
export { default as Fuelpump1 } from './assets/fuelpump1.jpg'
export { default as Fuelpump2 } from './assets/fuelpump2.jpg'
export { default as Fuelfilter } from './assets/fuelfilter.jpg'
export { default as Gearbox } from './assets/gearbox.jpeg'
export { default as Gearbox1 } from './assets/gearbox1.jpeg'
export { default as Oilchange } from './assets/oilchange.jpg'
export { default as Oilchange1 } from './assets/oilchange1.jpg'
export { default as Sparkplugs } from './assets/sparkplugs.jpg'
export { default as Sparkplugs1 } from './assets/sparkplugs1.jpg'
export { default as Sparkplugs2 } from './assets/sparkplugs2.jpg'
export { default as Tracking } from './assets/tracking.jpg'
export { default as Towing } from './assets/towing1.jpeg'
export { default as Alignment } from './assets/alignment1.jpg'
export { default as Brakepad } from './assets/brakepad.jpg'
export { default as Bulb1} from './assets/bulb1.jpg'
export { default as Bulb2} from './assets/bulb2.jpg'
export { default as Headlight} from './assets/headlights.jpg'
export { default as Beams} from './assets/beams.jpg'
export { default as Beams1} from './assets/beams1.jpg'
export { default as Beams2} from './assets/beams2.jpg'
export { default as Beams3} from './assets/beams3.jpg'